name: build-x86-64-immortalwrt-24.10.x

on:
  workflow_dispatch:
    inputs:
      luci_version:
        description: "选择luci版本"
        required: false
        default: "24.10.5"
        type: choice
        options:
          - 24.10.0
          - 24.10.1
          - 24.10.2
          - 24.10.3
          - 24.10.4
          - 24.10.5
      custom_router_ip:
        description: "请设置路由器的管理地址(仅首次安装生效；升级保留原配置时会忽略) 格式:192.168.x.1 或 10.x.x.1"
        required: true
        default: "192.168.100.1"
      include_docker:
        description: |
          是否编译 Docker 插件
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'
      enable_pppoe:
        description: "是否配置PPPoE拨号信息?"
        required: true
        default: 'no'
        type: choice
        options:
        - 'yes'
        - 'no'
      pppoe_account:
        description: "宽带账号 (若启用PPPoE)"
        required: false
      pppoe_password:
        description: "宽带密码 (若启用PPPoE)"
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set executable permissions
        run: chmod +x ${{ github.workspace }}/x86-64/build24.sh

      - name: Save Custom Router IP into OpenWrt files
        run: |
          mkdir -p "${{ github.workspace }}/custom"
          echo "${{ github.event.inputs.custom_router_ip }}" > "${{ github.workspace }}/custom/custom_router_ip.txt"
          echo "您设置的路由器管理地址是:${{ github.event.inputs.custom_router_ip }}（仅首次安装生效；升级保留配置时忽略）"

      - name: Build ImmortalWrt-x86-64-efi 24.10.x
        run: |
          include_docker="${{ github.event.inputs.include_docker }}"
          luci_version="${{ github.event.inputs.luci_version }}"
          echo "Building with fixed partition size from current build settings"
          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
            -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
            -v "${{ github.workspace }}/custom:/home/build/immortalwrt/files/etc/config" \
            -v "${{ github.workspace }}/x86-64/imm.config:/home/build/immortalwrt/.config" \
            -v "${{ github.workspace }}/shell:/home/build/immortalwrt/shell" \
            -v "${{ github.workspace }}/x86-64/build24.sh:/home/build/immortalwrt/build.sh" \
            -e PROFILE=512 \
            -e INCLUDE_DOCKER=$include_docker \
            -e ENABLE_PPPOE=${{ github.event.inputs.enable_pppoe }} \
            -e PPPOE_ACCOUNT=${{ github.event.inputs.pppoe_account }} \
            -e PPPOE_PASSWORD=${{ github.event.inputs.pppoe_password }} \
          immortalwrt/imagebuilder:x86-64-openwrt-${{ github.event.inputs.luci_version }} /bin/bash /home/build/immortalwrt/build.sh
          

      - name: Create info
        run: |
          cat > ${{ github.workspace }}/router-info.md <<EOF
          ## 📡 路由器后台信息
          <a href="https://wkdaily.cpolar.cn/archives/1">
           <img src="https://img.shields.io/badge/若下载慢可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
          </a>
          
          - 🏠 **后台地址**: ${{ github.event.inputs.custom_router_ip }}（升级保留配置时会沿用原 LAN 地址）
          - 👤 **用户名**: root
          - 🔑 **密码**: 无
          EOF

          if [ "${{ github.event.inputs.include_docker }}" == "yes" ]; then
            extra_content="#### 默认带docker"
            echo -e "\n$extra_content" >> ${{ github.workspace }}/router-info.md
          else
            echo -e "\n#### 不带docker" >> ${{ github.workspace }}/router-info.md
          fi

      - name: Upload ImmortWrt as release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Autobuild-x86-64
          body_path: ${{ github.workspace }}/router-info.md
          files: |
            ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.img.gz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}